name: CD - Deploy to AWS Lambda from S3

on:
  push:
    tags:
      - "v*"  # Triggers when a new release tag is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version from Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"  # Change as needed

      - name: Deploy Lambda from S3
        run: |
          aws lambda update-function-code \
            --function-name my-lambda-function \
            --s3-bucket my-deployment-bucket \
            --s3-key releases/${{ env.RELEASE_VERSION }}.zip

      - name: Verify Lambda Deployment
        run: |
          aws lambda get-function --function-name my-lambda-function
